#!/usr/bin/env python
# -*- coding: utf-8 -*-

import platform
import threading

from Cheese.cheese import CheeseBurger

"""
File generated by Cheese Framework

main file of Cheese Application
"""

if __name__ == "__main__":
    CheeseBurger.init()

    from src.tools.camera import *
    from src.tools.streamingOutput import *


    if (platform.system() != "Windows"):
        StreamingOutput.init()
        Camera.init()
        Camera.start_recording()

    from src.tools.arduinoControll import ArduinoController
    ArduinoController.init()

    from src.tools.socketServer import SocketServer
    socket_server = SocketServer()
    socket_thread = threading.Thread(target=socket_server.serve_forever)
    socket_thread.start()

    try:
        CheeseBurger.serveForever()
    finally:
        print("Camera stop")
        Camera.stop_recording()