#!/usr/bin/env python
# -*- coding: utf-8 -*-

from Cheese.cheese import CheeseBurger

"""
File generated by Cheese Framework

main file of Cheese Application
"""

if __name__ == "__main__":
    CheeseBurger.init()

    from src.tools.camera import *
    from src.tools.streamingOutput import *

    StreamingOutput.init()
    Camera.init()
    Camera.start_recording()

    try:
        CheeseBurger.serveForever()
    finally:
        print("Camera stop")
        Camera.stop_recording()